GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/8d199390-c7bf-42ae-add8-014597133192

########################

POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "q"
}

###

PATCH http://localhost:3333/courses/2
Content-Type: application/json

{
    "title": "Curso de Node.js - Atualizado"
}

###

PUT http://localhost:3333/courses/2
Content-Type: application/json

{
    "title": "Curso de Node.js - Atualizado",
    "description": "Curso de Node.js - Atualizado"
}

###

DELETE http://localhost:3333/courses/74a8219a-42be-405f-9898-382d593dc2a9
